require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VodkasController do

  # This should return the minimal set of attributes required to create a valid
  # Vodka. As you add validations to Vodka, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VodkasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vodkas as @vodkas" do
      vodka = Vodka.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vodkas).should eq([vodka])
    end
  end

  describe "GET show" do
    it "assigns the requested vodka as @vodka" do
      vodka = Vodka.create! valid_attributes
      get :show, {:id => vodka.to_param}, valid_session
      assigns(:vodka).should eq(vodka)
    end
  end

  describe "GET new" do
    it "assigns a new vodka as @vodka" do
      get :new, {}, valid_session
      assigns(:vodka).should be_a_new(Vodka)
    end
  end

  describe "GET edit" do
    it "assigns the requested vodka as @vodka" do
      vodka = Vodka.create! valid_attributes
      get :edit, {:id => vodka.to_param}, valid_session
      assigns(:vodka).should eq(vodka)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vodka" do
        expect {
          post :create, {:vodka => valid_attributes}, valid_session
        }.to change(Vodka, :count).by(1)
      end

      it "assigns a newly created vodka as @vodka" do
        post :create, {:vodka => valid_attributes}, valid_session
        assigns(:vodka).should be_a(Vodka)
        assigns(:vodka).should be_persisted
      end

      it "redirects to the created vodka" do
        post :create, {:vodka => valid_attributes}, valid_session
        response.should redirect_to(Vodka.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vodka as @vodka" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vodka.any_instance.stub(:save).and_return(false)
        post :create, {:vodka => { "name" => "invalid value" }}, valid_session
        assigns(:vodka).should be_a_new(Vodka)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vodka.any_instance.stub(:save).and_return(false)
        post :create, {:vodka => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vodka" do
        vodka = Vodka.create! valid_attributes
        # Assuming there are no other vodkas in the database, this
        # specifies that the Vodka created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vodka.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => vodka.to_param, :vodka => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested vodka as @vodka" do
        vodka = Vodka.create! valid_attributes
        put :update, {:id => vodka.to_param, :vodka => valid_attributes}, valid_session
        assigns(:vodka).should eq(vodka)
      end

      it "redirects to the vodka" do
        vodka = Vodka.create! valid_attributes
        put :update, {:id => vodka.to_param, :vodka => valid_attributes}, valid_session
        response.should redirect_to(vodka)
      end
    end

    describe "with invalid params" do
      it "assigns the vodka as @vodka" do
        vodka = Vodka.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vodka.any_instance.stub(:save).and_return(false)
        put :update, {:id => vodka.to_param, :vodka => { "name" => "invalid value" }}, valid_session
        assigns(:vodka).should eq(vodka)
      end

      it "re-renders the 'edit' template" do
        vodka = Vodka.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vodka.any_instance.stub(:save).and_return(false)
        put :update, {:id => vodka.to_param, :vodka => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vodka" do
      vodka = Vodka.create! valid_attributes
      expect {
        delete :destroy, {:id => vodka.to_param}, valid_session
      }.to change(Vodka, :count).by(-1)
    end

    it "redirects to the vodkas list" do
      vodka = Vodka.create! valid_attributes
      delete :destroy, {:id => vodka.to_param}, valid_session
      response.should redirect_to(vodkas_url)
    end
  end

end
